"use strict";
const cardArr = [
    {
        url: "./pages/10-ways-center.html",
        title: "Center Element",
        description: "10 Ways to Center element horizontally as well as Vertically",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/accent-color.html",
        title: "Accent Color",
        description: "Use of the accent color of the page",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/animated-accordion/index.html",
        title: "Animated Accordion",
        description: "Accordion with animation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/animated-background.html",
        title: "Animated Background",
        description: "Background that changes color continuously",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/animated-mouse-scrolling.html",
        title: "Animated Mouse Scrolling",
        description: "Mouse Scrolling Animation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/animated-search.html",
        title: "Animated Search",
        description: "Search Animation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/animated-text.html",
        title: "Animated Text",
        description: "Text Animation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/animation.html",
        title: "Animation",
        description: "Animation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/background-overlay.html",
        title: "Background Overlay",
        description: "Background Overlay",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/block-reveal-effect.html",
        title: "Block Reveal Effect",
        description: "Block Reveal Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/border-hover-effect.html",
        title: "Border Hover Effect",
        description: "Border Hover Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/box-animation.html",
        title: "Box Animation",
        description: "Box Animation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/bulma.html",
        title: "Bulma CSS",
        description: "Bulma CSS Tutorial",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/button-hover-effect.html",
        title: "Button Hover Effect",
        description: "Button Hover Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/button-hover-effect-2.html",
        title: "Button Hover Effect 2",
        description: "Button Hover Effect 2",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/button-hover-effect-3.html",
        title: "Button Hover Effect 3",
        description: "Button Hover Effect 3",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/buttons-hover-effect-4.html",
        title: "Buttons Hover Effect 4",
        description: "Buttons Hover Effect 4",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/button-sound-effect-audible-code.html",
        title: "Button Sound Effect Audible Code",
        description: "Button Sound Effect Audible Code",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/cake.html",
        title: "Cake",
        description: "Cake",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/cake-flip.html",
        title: "Cake flip",
        description: "Cake flip",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/calculator.html",
        title: "Calculator",
        description: "Calculator",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/clock/index.html",
        title: "Clock",
        description: "Clock",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/color-captcha/index.html",
        title: "Color Captcha",
        description: "Color Captcha",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/cool-link-effect.html",
        title: "Cool Link Effect",
        description: "Cool Link Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/css-gradient.html",
        title: "Css Gradient",
        description: "Css Gradient",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/css-grid-1.html",
        title: "Css Grid 1",
        description: "Css Grid 1",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/css-grid-2.html",
        title: "Css Grid 2",
        description: "Css Grid 2",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/css-grid-3.html",
        title: "Css Grid 3",
        description: "Css Grid 3",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/css-tutorial.html",
        title: "Css Tutorial",
        description: "Css Tutorial",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/dark-mode.html",
        title: "Dark Mode",
        description: "Dark Mode",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/email-validation/index.html",
        title: "Email Validation",
        description: "Email Validation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/fixed-contact-info.html",
        title: "Fixed Contact Info",
        description: "Fixed Contact Info",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/flexbox.html",
        title: "Flexbox",
        description: "Flexbox",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/floating-text-animation.html",
        title: "Floating Text Animation",
        description: "Floating Text Animation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/follow-mouse/index.html",
        title: "Follow Mouse",
        description: "Follow Mouse",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/form-design-layout/index.html",
        title: "Form Design Layout",
        description: "Form Design Layout",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/form.html",
        title: "Form",
        description: "Form",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/full-screen-pre-loader.html",
        title: "Full Screen Pre Loader",
        description: "Full Screen Pre Loader",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/full-screen-responsive-image-slider.html",
        title: "Full Screen Responsive Image Slider",
        description: "Full Screen Responsive Image Slider",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/game-connect-four.html",
        title: "Game Connect Four",
        description: "Game Connect Four",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/game-memory.html",
        title: "Game Memory",
        description: "Game Memory",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/github-api.html",
        title: "Github Api",
        description: "Github Api",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/glowing-shapes.html",
        title: "Glowing Shapes",
        description: "Glowing Shapes",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/hamburger-icon-animation.html",
        title: "Hamburger Icon Animation",
        description: "Hamburger Icon Animation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/hide-menu-on-scroll.html",
        title: "Hide Menu On Scroll",
        description: "Hide Menu On Scroll",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/how-to-add-preloader-to-website.html",
        title: "How To Add Preloader To Website",
        description: "How To Add Preloader To Website",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/image-hover-effect.html",
        title: "Image Hover Effect",
        description: "Image Hover Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/image-slider.html",
        title: "Image Slider",
        description: "Image Slider",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/image-upload.html",
        title: "Image Upload",
        description: "Image Upload & Show Image Preview",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/input-type.html",
        title: "Input Type",
        description: "Input Type",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/landing-page-with-smooth-scroll-effect.html",
        title: "Landing Page With Smooth Scroll Effect",
        description: "Landing Page With Smooth Scroll Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/landing.html",
        title: "Landing",
        description: "Landing",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/layout-design.html",
        title: "Layout Design",
        description: "Layout Design",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/layout-design-2.html",
        title: "Layout Design 2",
        description: "Layout Design 2",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/layout-design-3.html",
        title: "Layout Design 3",
        description: "Layout Design 3",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/layout-design-4.html",
        title: "Layout Design 4",
        description: "Layout Design 4",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/layout-design-5-star-wars.html",
        title: "Layout Design 5 Star Wars",
        description: "Layout Design 5 Star Wars",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/layout-design-6.html",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        title: "Layout Design",
        description: "Layout Design 6",
    },
    {
        url: "./pages/loading-screen.html",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        title: "Loading Screen",
        description: "Loading Screen",
    },
    {
        url: "./pages/my-calculator.html",
        title: "My Calculator",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "My Calculator",
    },
    {
        url: "./pages/mouse_trail.html",
        title: "Mouse Trail",
        description: "Mouse Trail",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/netflix.html",
        title: "Netflix",
        description: "Netflix",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/otp_input.html",
        title: "Otp Input",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Otp Input",
    },
    {
        url: "./pages/parallax-effect.html",
        title: "Parallax Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Parallax Effect",
    },
    {
        url: "./pages/parallax-simple.html",
        title: "Parallax Simple",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Parallax Simple",
    },
    {
        url: "./pages/photo-gallery.html",
        title: "Photo Gallery",
        description: "Photo Gallery",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/pokemon.html",
        title: "Pokemon",
        description: "Pokemon",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/pre-loader-bouncing-ball.html",
        title: "Pre Loader Bouncing Ball",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Pre Loader Bouncing Ball",
    },
    {
        url: "./pages/pre-loader-bubble-effect.html",
        title: "Pre Loader Bubble Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Pre Loader Bubble Effect",
    },
    {
        url: "./pages/pre-loader-spiner.html",
        title: "Pre Loader Spiner",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Pre Loader Spiner",
    },
    {
        url: "./pages/random-hex-color-code-generator.html",
        title: "Random Hex Color",
        description: "Random Hex Color",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/read-mouse-coordinates.html",
        title: "Read Mouse Coordinates",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Read Mouse Coordinates",
    },
    {
        url: "./pages/remove-all-css.html",
        title: "Remove All Css",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Remove All Css",
    },
    {
        url: "./pages/responsive-image-gallery.html",
        title: "Responsive Image Gallery",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Responsive Image Gallery",
    },
    {
        url: "./pages/responsive-navbar.html",
        title: "Responsive Navbar",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Responsive Navbar",
    },
    {
        url: "./pages/responsive-website.html",
        title: "Responsive Website",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Responsive Website",
    },
    {
        url: "./pages/scroll-indicator.html",
        title: "Scroll Indicator",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Scroll Indicator",
    },
    {
        url: "./pages/search.html",
        title: "Search",
        description: "Search",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/skewed-background.html",
        title: "Skewed Background",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Skewed Background",
    },
    {
        url: "./pages/slide-out-navigation.html",
        title: "Slide Out Navigation",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Slide Out Navigation",
    },
    {
        url: "./pages/snake-game.html",
        title: "Snake Game",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Snake Game",
    },
    {
        url: "./pages/switch.html",
        title: "Switch",
        description: "Switch",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/text-hover-effect.html",
        title: "Text Hover Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Text Hover Effect",
    },
    {
        url: "./pages/text-inside-circle.html",
        title: "Text Inside Circle",
        description: "Text Inside Circle",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/text-portrait-effect-on-mouse-over.html",
        title: "Text Portrait Effect On Mouse Over",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Text Portrait Effect On Mouse Over",
    },
    {
        url: "./pages/text-shadow.html",
        title: "Text Shadow",
        description: "Text Shadow",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/text-transform-number-effect.html",
        title: "Text Transform Number Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Text Transform Number Effect",
    },
    {
        url: "./pages/touch-event.html",
        title: "Touch Event",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Touch Event",
    },
    {
        url: "./pages/transitions.html",
        title: "Transitions",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Transitions",
    },
    {
        url: "./pages/transparent-navbar.html",
        title: "Transparent Navbar",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Transparent Navbar",
    },
    {
        url: "./pages/typewriter-effect.html",
        title: "Typewriter Effect",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Typewriter Effect",
    },
    {
        url: "./pages/vertical-centering.html",
        title: "Vertical Centering",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Vertical Centering",
    },
    {
        url: "./pages/world-clock.html",
        title: "World Clock",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "World Clock",
    },
    {
        url: "./pages/zoom.html",
        title: "Zoom",
        description: "Zoom",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
    },
    {
        url: "./pages/drag-n-drop/index.html",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        title: "Drag N Drop",
        description: "Drag N Drop",
    },
    {
        url: "./pages/glass-morphism/index.html",
        title: "Glass Morphism",
        created_at: new Date("2022-11-22"),
        updated_at: new Date("2022-11-22"),
        description: "Glass Morphism",
    },
    {
        url: "./pages/modal_dialog.html",
        title: "Modal Dialog",
        created_at: new Date("2023-05-20"),
        updated_at: new Date("2023-05-20"),
        description: "Modal Dialog",
    },
    {
        url: "./pages/individual_transform.html",
        title: "Individual Transform",
        created_at: new Date("2023-05-20"),
        updated_at: new Date("2023-05-20"),
        description: "Individual Transform",
    },
];
function createCard(e) {
    let card = document.createElement("a");
    card.href = e.url;
    card.className = "card";
    card.title = e.title;
    card.innerHTML = `
  <div>
    <h3>${e.title}</h3>
    <h5>${e.description}</h5>
    <p>Created at ${e.created_at.toLocaleDateString()}</p>
</div>
<div class="upper_card">
    <a href="https://github.com/Rohit19060/ex_web/blob/main/${e.url.replace(".", "")}" target="_blank" class="btn">Code</a>
</div>`;
    return card;
}
let searchELE = document.getElementById("search");
searchELE.addEventListener("input", (e) => {
    let search = e.target.value;
    let newCardArr = cardArr.filter((card) => card.title.toLowerCase().includes(search.toLowerCase()));
    let main = document.querySelector("main");
    newCardArr.sort((b, a) => b.created_at.getTime() - a.created_at.getTime())
        .reverse();
    main.innerHTML = "";
    newCardArr.forEach((card) => {
        main.appendChild(createCard(card));
    });
});
cardArr.sort((b, a) => b.created_at.getTime() - a.created_at.getTime())
    .reverse();
let main = document.createElement("main");
cardArr.forEach((card) => {
    main.appendChild(createCard(card));
});
document.body.appendChild(main);
//# sourceMappingURL=script.js.map